<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Sanchit-PC" name="com.app.qa.test.ProjectDashboardTest" tests="20" failures="3" timestamp="03 Feb 2019 23:08:28 GMT" time="116.615" errors="0">
  <testcase name="checkExportButtonVisibility" time="5.254" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="checkExportButtonDisabled" time="5.255" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="checkAddRecordButtonVisibility" time="5.253" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validateRowAlignment" time="5.363" classname="com.app.qa.test.ProjectDashboardTest">
    <failure type="java.lang.AssertionError" message="Test Failed - The page rows are not aligned to the left (Horizontally) as their x-axis values do not match expected [120] but found [105]">
      <![CDATA[java.lang.AssertionError: Test Failed - The page rows are not aligned to the left (Horizontally) as their x-axis values do not match expected [120] but found [105]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at com.app.qa.test.ProjectDashboardTest.validateRowAlignment(ProjectDashboardTest.java:138)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateRowAlignment -->
  <testcase name="checkAddRecordButtonDisabled" time="5.173" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validatePageHeaderText" time="5.262" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validatePageHTMLTitle" time="5.207" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validateAccountingStatistics" time="6.059" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validateAdministrationStatistics" time="5.951" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validateMarketingStatistics" time="6.016" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validateSalesStatistics" time="7.861" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validateProductionStatistics" time="5.916" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validateArchivedStatistics" time="5.971" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validateNewStatistics" time="5.985" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validateWorkingStatistics" time="5.993" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validateDeliveredStatistics" time="5.950" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validateStatusUpdateStatistics" time="5.760" classname="com.app.qa.test.ProjectDashboardTest">
    <failure type="java.lang.AssertionError" message="Test Failed - Statistics are not getting updated on updating the status of a record! expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Test Failed - Statistics are not getting updated on updating the status of a record! expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.app.qa.test.ProjectDashboardTest.validateStatusUpdateStatistics(ProjectDashboardTest.java:107)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateStatusUpdateStatistics -->
  <testcase name="validateRecordUpdateSaveOnRefresh" time="6.558" classname="com.app.qa.test.ProjectDashboardTest">
    <failure type="java.lang.AssertionError" message="Test Failed - The updates made to the record were not refelected after page refresh!">
      <![CDATA[java.lang.AssertionError: Test Failed - The updates made to the record were not refelected after page refresh!
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.assertNotEquals(Assert.java:1157)
at com.app.qa.test.ProjectDashboardTest.validateRecordUpdateSaveOnRefresh(ProjectDashboardTest.java:114)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateRecordUpdateSaveOnRefresh -->
  <testcase name="validateFeedbackOnUpdate" time="5.944" classname="com.app.qa.test.ProjectDashboardTest"/>
  <testcase name="validateBudgetFormatOnUpdate" time="5.884" classname="com.app.qa.test.ProjectDashboardTest"/>
</testsuite> <!-- com.app.qa.test.ProjectDashboardTest -->
